### ISSUE TITLE
[Roadmap] GLake checklist

### ISSUE THREAD

**Issue by ruizhang1230** [intelligent-machine-learning/glake#14]
# Training

- [ ] Multi-stream Memory Reuse: Done, will be released
- [ ] Compatible with Expandable Segment
- [ ] Memory Pattern Profiling tool
- [ ] DoubleOverlapping(for finetune): Done, will be released
- [ ] Multipath with Specific Scenario
- [ ] Compression (Lossless/Lossy for finetune)

# Inference

- [ ] LLM KV Cache optimization: Almost Done, will be released
- [ ] MoE Inference Optmization
- [ ] Other Optimization for Specific Scenario (not fragmentation)

# Refactor

- [ ] Support TensorFlow
- [ ] Support ONNX RUNTIME
